import item1 from "./images/item-1.jpeg";

const cart = [{
        id: 1,
        name: "buttermilk pancakes",
        category: "breakfast",
        price: 15.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723870/item-1_apln3b.jpg",
        description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
        isSelected: true,
    },
    {
        id: 2,
        name: "diner double",
        category: "lunch",
        price: 13.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723871/item-2_ctg4db.jpg",
        description: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing.`,
        isSelected: false,
    },
    {
        id: 3,
        name: "godzilla milkshake",
        category: "shakes",
        price: 6.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-3_pr5yo2.jpg",
        description: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
        isSelected: false,
    },
    {
        id: 4,
        name: "country delight",
        category: "breakfast",
        price: 20.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-4_sd0dvn.jpg",
        description: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
        isSelected: false,
    },
    {
        id: 5,
        name: "egg attack",
        category: "lunch",
        price: 22.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-5_bujvlo.jpg",
        description: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
        isSelected: false,
    },
    {
        id: 6,
        name: "oreo dream",
        category: "shakes",
        price: 18.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-6_s1yemp.jpg",
        description: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
        isSelected: false,
    },
    {
        id: 7,
        name: "bacon overflow",
        category: "breakfast",
        price: 8.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-7_vuhc43.jpg",
        description: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
        isSelected: false,
    },
    {
        id: 8,
        name: "american classic",
        category: "lunch",
        price: 12.99,
        img: "",
        description: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
        isSelected: false,
    },
    {
        id: 9,
        name: "quarantine buddy",
        category: "shakes",
        price: 16.99,
        img: "https://res.cloudinary.com/gmkumaran87/image/upload/v1622723883/item-9_ymxg6b.jpg",
        description: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
        isSelected: false,
    },
];
export default cart;